# Generated by Django 5.1.5 on 2025-02-05 19:00

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = []

    operations = [VectorExtension()]
